Update Proxyalma

diff --git a/Proxyalma b/Proxyalma
--- a/Proxyalma
+++ b/Proxyalma
@@ -1,79 +1,82 @@
 #!/bin/bash
 
 random() {
-    tr </dev/urandom -dc A-Za-z0-9 | head -c5
-    echo
+tr </dev/urandom -dc A-Za-z0-9 | head -c5
+echo
 }
 
 array=(1 2 3 4 5 6 7 8 9 0 a b c d e f)
 gen64() {
-    ip64() {
-        echo "${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}"
-    }
-    echo "$1:$(ip64):$(ip64):$(ip64):$(ip64)"
+ip64() {
+echo "${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}"
+}
+echo "$1:$(ip64):$(ip64):$(ip64):$(ip64)"
 }
 
 install_3proxy() {
-    echo "Installing 3proxy"
-    URL="https://github.com/3proxy/3proxy/releases/download/3proxy-0.9.4/3proxy-0.9.4.tgz"
-    wget -qO- $URL | tar -xzf-
-    cd 3proxy-0.9.4
-    make -f Makefile.Linux
-    mkdir -p /usr/local/etc/3proxy/{bin,logs,stat}
-    cp ./bin/3proxy /usr/local/etc/3proxy/bin/
-    cp ./scripts/3proxy.service /etc/systemd/system/
-    systemctl daemon-reload
-    systemctl enable 3proxy
-    cd $WORKDIR
+echo "Installing 3proxy"
+URL="https://github.com/3proxy/3proxy/releases/download/3proxy-0.9.4/3proxy-0.9.4.tgz"
+wget -qO- $URL | tar -xzf-
+cd 3proxy-0.9.4
+make -f Makefile.Linux
+mkdir -p /usr/local/etc/3proxy/{bin,logs,stat}
+cp ./bin/3proxy /usr/local/etc/3proxy/bin/
+cp ./scripts/3proxy.service /etc/systemd/system/
+systemctl daemon-reload
+systemctl enable 3proxy
+cd $WORKDIR
 }
 
 gen_3proxy() {
-    cat <<EOF
+cat <<EOF
 daemon
 nscache 65536
 timeouts 1 5 30 60 180 1800 15 60
 setgid 65535
 setuid 65535
 
+Increase stack size to prevent crashes
+stacksize 8388608
+
 users $(awk -F "/" 'BEGIN{ORS="";} {print $1 ":CL:" $2 " "}' ${WORKDATA})
 
-$(awk -F "/" '{print "auth strong\n" \
-"allow " $1 "\n" \
+$(awk -F "/" '{print "auth strong\n"
+"allow " $1 "\n"
 "socks -6 -p" $4 " -i" $3 " -e"$5"\n"}' ${WORKDATA})
 EOF
 }
 
 gen_proxy_file_for_user() {
-    cat >proxy.txt <<EOF
+cat >proxy.txt <<EOF
 $(awk -F "/" '{print $3 ":" $4 ":" $1 ":" $2 }' ${WORKDATA})
 EOF
 }
 
 print_proxy() {
-    echo "Proxy is ready! Format IP:PORT:LOGIN:PASS"
-    echo "Here are your proxy details:"
-    cat proxy.txt
+echo "Proxy is ready! Format IP:PORT:LOGIN:PASS"
+echo "Here are your proxy details:"
+cat proxy.txt
 }
 
 gen_data() {
-    seq $FIRST_PORT $LAST_PORT | while read port; do
-        echo "usr$(random)/pass$(random)/$IP4/$port/$(gen64 $IP6)"
-    done
+seq $FIRST_PORT $LAST_PORT | while read port; do
+echo "usr$(random)/pass$(random)/$IP4/$port/$(gen64 $IP6)"
+done
 }
 
 gen_iptables() {
-    cat <<EOF
-    $(awk -F "/" '{print "iptables -I INPUT -p tcp --dport " $4 "  -m state --state NEW -j ACCEPT"}' ${WORKDATA}) 
+cat <<EOF
+$(awk -F "/" '{print "iptables -I INPUT -p tcp --dport " $4 " -m state --state NEW -j ACCEPT"}' ${WORKDATA})
 EOF
 }
 
 gen_ifconfig() {
-    INTERFACE=$(ip -6 addr | awk '/inet6/{print $NF}' | head -n1)
-    if [ -z "$INTERFACE" ]; then
-        echo "No IPv6 interface found. Skipping IPv6 configuration."
-        return
-    fi
-    cat <<EOF
+INTERFACE=$(ip -6 addr | awk '/inet6/{print $NF}' | head -n1)
+if [ -z "$INTERFACE" ]; then
+echo "No IPv6 interface found. Skipping IPv6 configuration."
+return
+fi
+cat <<EOF
 $(awk -F "/" '{print "ip -6 addr add " $5 "/64 dev '"$INTERFACE"'"}' ${WORKDATA})
 EOF
 }
@@ -117,10 +120,10 @@ EOF
 
 chmod +x /etc/rc.local
 
-# Attempt to run the rc.local script
+Attempt to run the rc.local script
 if ! bash /etc/rc.local; then
-    echo "Error occurred while running rc.local. Please check the network interface configuration."
-    exit 1
+echo "Error occurred while running rc.local. Please check the network interface configuration."
+exit 1
 fi
 
 echo "Restarting 3proxy..."
